name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  stale:
    runs-on: github-ubuntu-latest-s
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. If there is no activity in the next 7 days it will be closed automatically'
          stale-pr-label: 'stale'
          days-before-stale: 7
          days-before-close: 7
          exempt-pr-labels: 'do-not-close'
